### PR TITLE
[Resolves #9] Cleanup rubocop todo

### LINKED ISSUE #9: Rubocop cleanup
I believe that for the future of this project we should ensure code consistency. I propose we run perx-rubocop (which i also maintain)

### PR DESCRIPTION
**Pull request by rpbaltazar**

### CODE REVIEW

**Comment by rpbaltazar** [comment]
@jean-francois-labbe I'm generally a big fan of standards. I maintain the gem 'perx-rubocop` that is the one I usually use as default settings. Since you've been investing your time in this as well, do you have any issues with it?

**Comment by jean-francois-labbe** [comment]
> @jean-francois-labbe I'm generally a big fan of standards. I maintain the gem 'perx-rubocop` that is the one I usually use as default settings. Since you've been investing your time in this as well, do you have any issues with it?

@rpbaltazar That's a really good idea, to ease contribution the code must comply with a standard. I'm used to `rubocop` `standardrb` and `rufo`. whatever the tool you choose, I'm ok with that.

**Comment by jean-francois-labbe** [comment]
@rpbaltazar One thing that would be nice is to fix the travis-ci config in order to have a Green CI status, it would reassure users and enable faster tests status analysis (today I need to go check why the status is Red), easier merge request approval.

**Comment by rpbaltazar** [comment]
I’ll wrap up the rubocop and have it merged then. 
I have not checked right now, but The red was because of a bug in one of the rails versions. I think that for that specific case we can move it to the section of the “allowed to fail” until the rails fix version is released.

**Pull request merged**
