### PR TITLE
Prepare Release - 2.8.0

### LINKED ISSUE #66: Use a transaction for Apartment::Tenant.create
## Steps to reproduce

1. Have tenant creating fail in the middle (by missing functions for example)

## Expected behavior

1. Nothing gets created in the schema

## Actual behavior

1. You get leftover objects

As with PostgreSQL DDL is transaction safe, the schema creation should be wrapped with a transaction.

## System configuration

* Database:  PostgreSQL 10

* Apartment version: 2.6.1

* Apartment config (in `config/initializers/apartment.rb` or so):

  * `use_schemas`: true
  * `persistent_schemas`: %w[shared_extensions]

* Rails (or ActiveRecord) version: 6.0.2.1

* Ruby version: 2.7.0

### LINKED ISSUE #86: error running db:seed task
## Steps to reproduce

rails db:drop db:create db:migrate db:seed

## Expected behavior

(truncated)
        [WARNING] - The list of tenants to migrate appears to be empty. This could mean a few things:

          1. You may not have created any, in which case you can ignore this message
          2. You've run `apartment:migrate` directly without loading the Rails environment
            * `apartment:migrate` is now deprecated. Tenants will automatically be migrated with `db:migrate`

        Note that your tenants currently haven't been migrated. You'll need to run `db:migrate` to rectify this.
Seeding myapp_development_mygroup tenant

## Actual behavior

(truncated)
        [WARNING] - The list of tenants to migrate appears to be empty. This could mean a few things:

          1. You may not have created any, in which case you can ignore this message
          2. You've run `apartment:migrate` directly without loading the Rails environment
            * `apartment:migrate` is now deprecated. Tenants will automatically be migrated with `db:migrate`

        Note that your tenants currently haven't been migrated. You'll need to run `db:migrate` to rectify this.
Creating myapp_development_mygroup tenant
Error while creating tenant myapp_development_mygroup: Mysql2::Error: Can't create database 'myapp_development_mygroup'; database exists
Seeding myapp_development_mygroup tenant

(Seems like the application tries to create a database before running the seed command.)
## System configuration

* **Database:** Mysql 8.0.20

* **Apartment version:** 2.7.1

* **Apartment config (in `config/initializers/apartment.rb` or so):**  #config.use_schemas = true (line is commented)

* **Rails (or ActiveRecord) version:** 6.0.3.2

* **Ruby version:** 2.7.1

I'm getting an error while running db:seed. It looks like the application tries to create a database before running the seed command. Everything runs ok at version 2.7.0

Due to this commit:
https://github.com/rails-on-services/apartment/pull/84/commits/b6af077ceb4b16b3a5e27c0126f8d645107b5a24
[apartment.zip](https://github.com/rails-on-services/apartment/files/4920274/apartment.zip)

### LINKED ISSUE #98: Improve changelog automatic generation
Currently, changelog is being committed to development as it is the main development branch. This causes some issues because it won't be updated on releases properly.
If we publish directly to master, without updating development first, there will be no changelog tracked in the development branch which is shown by default when people come into the repository.

Update the changelog action to push the changelog to the proper branch(es)

### LINKED ISSUE #121: Rails 6.1 compatibility
## Steps to reproduce

* Use `gem 'rails', '~> 6.1.rc1'` and `gem 'ros-apartment', require: 'apartment'` in the same application

## Expected behavior

It lets you install the bundle.

## Actual behavior

It fails due to the [current strict requirement of a Rails version < 6.1](https://github.com/rails-on-services/apartment/blob/db454b562cf1d993831415394b233c21a04efd8c/ros-apartment.gemspec#L30)

## Proposed Change

Specs run fine when relaxing the Rails version requirement to `< 6.2` in the gemspec. Would love to open a PR with this change if that is ok with current release standards. Cheers!

### LINKED ISSUE #123: Tenant creation in transaction makes some test cases fail
## Steps to reproduce

Run the test suite with use_transactional_fixtures set to true. Creating a new tenant in a test will raise an exception because a transaction is already in place

## Expected behavior

Should pass the tests and not raise exception 

* Database: (Tell us what database and its version you use.)

postgresql 12.4

* Apartment version:

development branch

* Apartment config (in `config/initializers/apartment.rb` or so):

  * `use_schemas`: `true`

* Rails (or ActiveRecord) version:

6.0.3.4

* Ruby version:

2.7.1

### PR DESCRIPTION
**Pull request by rpbaltazar**
- Resolves #98 - Trying to generate an automatic changelog - #99
- Resolves #86 - Fixes seeding errors - #87
- Resolves #66 - Uses a transaction to create a tenant - #69
- Resolves #121 - Relaxes dependencies to allow rails 6.1 - #122
- Resolves #123 - When tests run in a transaction, new tenants in tests fail to create - #124
- Reverted unsafe initializer - #118

### CODE REVIEW

**Comment by rpbaltazar** [comment]
@lunks and @louim if you have a chance to test the development version against your platforms, i'd appreciate. I've ran it against ours and all tests are green, so i'd be happy to release this.

**Comment by lunks** [comment]
You should add my PR to the list too, it was on `master` before. I'll test it when I have a chance.

**Comment by lunks** [comment]
@rpbaltazar I'd like to talk about the error when trying to create an already existent schema.

The one that starts with:

```
Creating localhost tenant                                                                                                           
Could not log "sql.active_record" event. ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is 
aborted, commands ignored until end of transaction block                                                                            
 ["/Users/lunks/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.2.0/lib/patches/db/pg.rb:110:in `exec'", "/U
sers/lunks/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.2.0/lib/patches/db/pg.rb:110:in `async_exec'", "/
Users/lunks/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql
/database_statements.rb:65:in `block (2 levels) in query'", "/Users/lunks/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7
```

Two things concerne me on it:
* `Could not log "sql.active_record" event` looks like an error that should be fixed.
* The whole stack trace output might not be an error and expected, but it's confusing to me as an user. Ideally we should supress it but I wonder if we're doing something wrong given any commands will be ignored for this transaction.

**Comment by rpbaltazar** [comment]
> You should add my PR to the list too, it was on `master` before. I'll test it when I have a chance.

I've picked them and added it to the development branch, else we'd have a bunch of unresolved conflicts.

**Comment by rpbaltazar** [comment]
I looked at this and it seems to be a side consequence of failing to create the tenant. The Logger is rescuing all exceptions and logging all that output that you see, including the stack trace.

https://api.rubyonrails.org/v5.1.7/classes/ActiveSupport/LogSubscriber.html#method-i-finish

I'm curious about the tenant creation error. Is that on purpose for demoing the sql.active_error logging problems or something related to the current development branch?

**Comment by lunks** [comment]
> > You should add my PR to the list too, it was on `master` before. I'll test it when I have a chance.
> 
> I've picked them and added it to the development branch, else we'd have a bunch of unresolved conflicts.

I mean, to the changelog.

**Comment by rpbaltazar** [comment]
> @rpbaltazar I'd like to talk about the error when trying to create an already existent schema.

@lunks just to make sure, was this an expected error that you wanted to show me the log for or was an unexpected error and the log was just a side thing?

**Comment by lunks** [comment]
> > @rpbaltazar I'd like to talk about the error when trying to create an already existent schema.
> 
> @lunks just to make sure, was this an expected error that you wanted to show me the log for or was an unexpected error and the log was just a side thing?

The error is expected (my tenant already exists) but it's pretty bad to have it shown like that.

**Comment by rpbaltazar** [comment]
> The error is expected (my tenant already exists) but it's pretty bad to have it shown like that. I think we should solve the active record log issue and handle this error more gracefully so users don't panic when seeing it.

all clear. I think that for the sake of moving forward, we can open a ticket to address this and in the meantime release the gem version that fixes the unsafe initializer, which seems a more concerning issue

**Comment by lunks** [comment]
> > The error is expected (my tenant already exists) but it's pretty bad to have it shown like that. I think we should solve the active record log issue and handle this error more gracefully so users don't panic when seeing it.
> 
> all clear. I think that for the sake of moving forward, we can open a ticket to address this and in the meantime release the gem version that fixes the unsafe initializer, which seems a more concerning issue

Feel free to do so!

**Pull request merged**
