### PR TITLE
Support rails 7.2

### PR DESCRIPTION
**Pull request by npezza93**

### CODE REVIEW

**Comment by npezza93** [comment]
@mnovelo this is ready to go now

**Review by mnovelo — APPROVED** [review]

**Comment by KoenSengers** [comment]
@mnovelo could you create a new release for this issue?

**Comment by mnovelo** [comment]
Yes, soon. I'm looking to include #276, #184, and #182 in the next release too

**Comment by KoenSengers** [comment]
@mnovelo any progress?

**Comment by martinbarilik** [comment]
Thanks to everyone involved in Rails 7.2 support :)

**Comment by KoenSengers** [comment]
@mnovelo any update on your progress?

**Comment by mnovelo** [comment]
@KoenSengers yes, I'm working on getting the specs to pass for newer versions of Postgres (15, 16, and 17). I won't be able to support jruby for Rails 7.2

https://github.com/rails-on-services/apartment/pull/292

**Pull request merged**
