### PR TITLE
Refactor unsubscribe logic to avoid unsubscribing other listeners

### LINKED ISSUE #189: Remove ActiveSupport::Notifications#unsubscribe
Copied from the [Original PR](https://github.com/rails-on-services/apartment/pull/186)

Hi Rails-on-Services! 👋

I'm a developer on the New Relic Ruby Agent team. I recently discovered that the config.active_record_log option disables all Datastore recording for our newrelic_rpm gem.

The culprit seems to be the line removed in this PR. Calling #unsubscribe on ActiveSupport::Notifications interferes with the strategy many gems use to instrument ActiveRecord's behavior.

My intention behind this PR is to start a conversation about why the #unsubscribe method is called and if we can find another way achieve its goal.

Thanks for your time and for picking up the torch on this great library. 🔥

### PR DESCRIPTION
**Pull request by rpbaltazar**
Resolves #189

### CODE REVIEW

**Comment by rpbaltazar** [comment]
@kaylareopelle please take a look at this PR and help me check if this does not impact your gem's implementation. I've tried to follow a similar approach used by lograge to unsubscribe specific event listener

**Comment by rpbaltazar** [comment]
I have looked through the new_relic's gem source code and I don't think you're relying anyhow on ActiveRecord::LogSubscriber specifically, so I think this is a safe solution to push forward. Please re-open the ticket if that is not the case.

**Comment by kaylareopelle** [comment]
@rpbaltazar  - Thank you for this fix! It looks like it should avoid the issues we were previously seeing with the agent. My apologies for the lack of response over the weekend! I'll share this with a customer that raised the conflict and let you know how it goes.

**Comment by rpbaltazar** [comment]
No problem. My time available for OSS varies a lot throughout the year, thus trying to power through a few issues once i have time avail. Thank you for this! 🔥

**Pull request merged**
