### PR TITLE
Update the LogSubscriber sql method to match rails' and restore binds display

### PR DESCRIPTION
**Pull request by louim**
The gem is overwriting the SQL logger to add apartment specific info when `active_record_log` is enabled. However, the method hasn't been update to match the source one in Rails and wasn't displaying the `binds` correctly. I updated method with the latest version [lifted directly from rails here](https://github.com/rails/rails/blob/e44b3419d44b5fa6e66305fe703f34bb63932593/activerecord/lib/active_record/log_subscriber.rb#L22-L50) and adapted to insert the extra logging: 
**Before the fix:**
```
    User Load (1.3ms) SELECT "public"."users".* FROM "public"."users" WHERE "public"."users"."email" = $1 AND "public"."users"."provider" = $2 LIMIT $3
  ↳ app/controllers/graphql_controller.rb:16:in `execute'
```
**After the fix:**
```
  User Load (0.9ms)  SELECT "public"."users".* FROM "public"."users" WHERE "public"."users"."email" = $1 AND "public"."users"."provider" = $2 LIMIT $3  [["email", "my_email@example.com"], ["provider", "email"], ["LIMIT", 1]]
  ↳ app/controllers/graphql_controller.rb:16:in `execute'
```

Because the gem overwrites the `sql` method on the `LogSubscriber`, it is prone to breakage when the source method changes. It may also not be backward compatible with previous rails versions. This is the "simple" fix. I haven't looked too much into it. Maybe it would be possible to prepend the module only when the `active_record_log` is enabled to reduce the chance of breakage to user who aren't using the extra logging.

### CODE REVIEW

**Comment by GaboFDC** [comment]
@louim could you check why the CI failed? my pr seems to have the same problems, seems like the dbs for some test are not working fine, but I was unable to check deeper.

**Comment by lunks** [comment]
Hey @louim are you following with this PR? If not, I can take over.

**Comment by louim** [comment]
Hey @lunks, thanks for the nudge, I hadn't seen that the build was fixed on develop. I rebased the branch and hopefully the tests should pass.

**Comment by rpbaltazar** [comment]
Closing in favor of #125

**Pull request closed without merging**
