### PR TITLE
Avoid early connection

### PR DESCRIPTION
**Pull request by fsateler**
Fixes https://github.com/influitive/apartment/issues/607 in a more general way than #16

### CODE REVIEW

**Comment by rpbaltazar** [comment]
The code seems to make sense to me, but it breaks all the specs. can you please take a look a it?

**Comment by fsateler** [comment]
I could not understand the failure completely, but it appears to be related to recursive calls to connection. I have solved the problem by ensuring we only init once per Reload.

**Comment by rpbaltazar** [comment]
I'm opening a new PR #50 with the changes because there has been no reply. I'll look at it and see if i can fix the issue.

**Comment by fsateler** [comment]
Sorry, I dropped the ball. The problem seems to be that `init` does not invoke `process_excluded_models`. Maybe it should? I have added a switch to the current tenant, lets see if the tests passes. Not sure if the fix makes sense.

**Comment by fsateler** [comment]
OK, so it seems the problem was instead I was relying on an instance variable in `ActiveRecord::Base`. Switching that to a variable in `Apartment::Tenant` fixed most of the tests. To fix the remaining ones, I had to move `init` to the adapters so that the postgres adapter can set the schema search path. I don't know why that is needed but it doesn't seem wrong either.

**Comment by fsateler** [comment]
Rubocop failure appears to be configuration-related.

**Comment by rpbaltazar** [comment]
Thank you. Will get it merged and will start testing against our test suite, as well as out staging env

**Pull request merged**
